# Site settings
title: NORTH AMERICAN RAIL SAFETY
email: info@narailsafety.com

description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
address: "box 1282"

# Build settings
markdown: kramdown
