# Site settings
title: NORTH AMERICAN RAIL SAFETY
email: info@narailsafety.com

description: Our Company North American Rail Safety recognizes the need to teach cutting edge safe railroading to employees the public and to employers to reduce rail incidents.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://narailsafety.com" # the base hostname & protocol for your site
address: "Box 1282 <br/> Yorkton, SK S3N 2X3"

# Build settings
markdown: kramdown 
